### PR TITLE
feat: different targetSafe and receiver

### PR DESCRIPTION
**Pull request by meetmangukiya**

### CODE REVIEW

**Review by mfw78 — APPROVED** [review]
LGTM

**Review by fleupold — APPROVED** [review]
Looks good

**Review by fleupold — APPROVED** [review]
Sorry meant to approve. @meetmangukiya could you add a PR description that gives context for why this change is necessary?

**Comment by meetmangukiya** [comment]
in production the receiver and the safe that this module gets enabled on are different addresses

**Pull request merged**
